apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  namespace: plex
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/meireles/Development/kube-plex/files