apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  namespace: plex
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  storageClassName: vsphere-nashdd2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  csi:
    driver: csi.vsphere.vmware.com
    volumeHandle: pvc-plexconfig
