apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Match the storage capacity with your PV