apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: plex
spec:
  storageClassName: vsphere-nas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi  # Match the storage capacity with your PV

