apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: plex
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  vsphereVolume:
    volumePath: /plex-data

