apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcode-pvc
  namespace: plex
spec:
  storageClassName: vsphere-nashdd2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Match the storage capacity with your PV

