apiVersion: v1
kind: PersistentVolume
metadata:
  name: transcode-pv
  namespace: plex
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/meireles/Development/kube-plex/files